version: 2

sources:
  - name: staging
    database: valued-bastion-411614
    schema: dbt_taxi

    tables:
      - name: green_tripdata_ext
      - name: yellow_tripdata_ext
      - name: fhv_tripdata_ext
  